id: P003203
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5666
  title: 'ལེགས་སྦྱར་དང་མར་མེ་སྨོན་ལམ། '
  author: ''
  volumes:
    bf9f71ef7244429884c362c762a18fd8:
      image_group_id: I1KG5676
      title: ''
      volume_number: 1
      total_pages: 80
