id: I05E999AF
legacy_id: P003203
ocr_import_info:
  bdrc_scan_id: W1KG5666
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T11:58:00'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:20:39.734512+00:00'
last_modified: 2022-09-01 01:20:46.989301
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5666
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5666
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལེགས་སྦྱར་དང་མར་མེ་སྨོན་ལམ།
statistics:
  ocr_word_mean_confidence_index: 0.7648094733636721
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG5676:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5676
      total_pages: 80
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5676.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.7648094733636721
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
