id: I05E999AF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T11:58:51+00:00'
last_modified: '2022-06-07T18:22:33.163968+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5666
  title: 'ལེགས་སྦྱར་དང་མར་མེ་སྨོན་ལམ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E0D5:
      image_group_id: I1KG5676
      title: ''
      total_pages: 80
      order: 1
      base_file: E0D5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
